#!/usr/bin/env zsh
# fetch-pristine.zsh — fetch the exact sources THIS MACHINE runs.
#
# Resolves the nixpkgs rev pinned in the system flake (~/nixos-config by
# default) and materializes the pristine sources from the same rev the Nix
# store used to build them:
#
#   build/pristine/bluez/                          — pristine BlueZ tree (e.g. 5.86)
#   build/pristine/kernel/drivers/hid/hid-nintendo.c — pristine driver for the running kernel
#   src/MANIFEST.md                                — pin record (rev, version, store path, URL)
#
# The reviewed artifacts (full patched files + patches) live under src/ and
# are tracked; the pristine trees here are throwaway reference for diffing and
# rebuilding, which is why they are gitignored.
#
# Reproducible: after every system upgrade (~6 months), re-run this and the
# sources track whatever the new flake.lock pins. Nothing is downloaded from
# guesswork; the store path is content-addressed from the pinned rev.
#
# Usage:
#   tools/fetch-pristine.zsh           # fetch if src/ is empty
#   tools/fetch-pristine.zsh --force   # overwrite existing trees (DESTROYS EDITS!)
#   NIXOS_CONFIG=/path tools/fetch-pristine.zsh
#
# Prereqs: nix + jq on PATH (both present on stock NixOS).

set -euo pipefail

NIXOS_CONFIG="${NIXOS_CONFIG:-$HOME/nixos-config}"
LOCK="$NIXOS_CONFIG/flake.lock"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BLUEZ_DIR="$ROOT/build/pristine/bluez"
KERNEL_DIR="$ROOT/build/pristine/kernel"
MANIFEST="$ROOT/src/MANIFEST.md"

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

die() { print -u2 "fetch-pristine: $*"; exit 1; }

command -v nix >/dev/null || die "nix not found on PATH"
command -v jq  >/dev/null || die "jq not found on PATH"
[[ -f "$LOCK" ]] || die "flake.lock not found at $LOCK (set NIXOS_CONFIG=...)"
grep -q '"nixpkgs"' "$LOCK" || die "no nixpkgs input in $LOCK"

# --- resolve the pinned nixpkgs -------------------------------------------------
NP_REV="$(jq -r '.nodes.nixpkgs.locked.rev // empty' "$LOCK")"
NP_NAR="$(jq -r '.nodes.nixpkgs.locked.narHash // empty' "$LOCK")"
[[ -n "$NP_REV" ]] || die "no .nodes.nixpkgs.locked.rev in $LOCK"
NIXPKGS="github:NixOS/nixpkgs/$NP_REV"
print "nixpkgs pin: $NIXPKGS"
print "       nar:  $NP_NAR"

# --- guard against clobbering edited trees -----------------------------------
if [[ $FORCE -eq 0 ]]; then
  for d in "$BLUEZ_DIR" "$KERNEL_DIR"; do
    if [[ -d "$d" ]] && (( $(find "$d" -mindepth 1 | wc -l) > 0 )); then
      die "$d is not empty — refuse to overwrite. Use --force to replace (drops everything)."
    fi
  done
fi

eval_get() {  # eval_get "<attr>" -> raw string
  timeout 600 nix eval --raw "$NIXPKGS#$1" 2>/dev/null || die "nix eval $1 failed"
}

build_get() {  # build_get "<attr>" -> store path
  timeout 900 nix build --no-link --print-out-paths "$NIXPKGS#$1" 2>/dev/null
}

# --- BlueZ -------------------------------------------------------------------
BLUEZ_VER="$(eval_get 'bluez.version')"
BLUEZ_URL="$(eval_get 'bluez.src.url')"
BLUEZ_TAR="$(build_get 'bluez.src')" || die "nix build bluez.src failed"
BLUEZ_SHA="$(sha256sum "$BLUEZ_TAR" | cut -d' ' -f1)"
print "BlueZ: $BLUEZ_VER  ($BLUEZ_URL)"
print "  store: $BLUEZ_TAR  sha256: $BLUEZ_SHA"

# --- kernel / hid-nintendo.c -------------------------------------------------
KVER_ATTR="linuxPackages.kernel"
KVER="$(eval_get "$KVER_ATTR.version")"
KURL="$(eval_get "$KVER_ATTR.src.url")"
KTAR="$(build_get "$KVER_ATTR.src")" || die "nix build kernel.src failed"
KSHA="$(sha256sum "$KTAR" | cut -d' ' -f1)"
print "kernel: $KVER  ($KURL)"
print "  store: $KTAR  sha256: $KSHA"

RUNNING="$(uname -r)"
if [[ "$KVER" != "$RUNNING" ]]; then
  print -u2 "WARNING: running kernel is $RUNNING but pinned nixpkgs provides $KVER —"
  print -u2 "         the rebooted kernel after next switch may differ. Fetching $KVER anyway."
fi

# --- unpack ------------------------------------------------------------------
rm -rf "$BLUEZ_DIR" "$KERNEL_DIR"
mkdir -p "$BLUEZ_DIR" "$KERNEL_DIR"

tar -xf "$BLUEZ_TAR" -C "$BLUEZ_DIR" --strip-components=1
tar -xf "$KTAR" -C "$KERNEL_DIR" --wildcards '*/drivers/hid/hid-nintendo.c' --strip-components=1

[[ -f "$KERNEL_DIR/drivers/hid/hid-nintendo.c" ]] || die "hid-nintendo.c not where expected in kernel tarball"

# --- manifest ----------------------------------------------------------------
{
  print "# Pristine source manifest (generated by tools/fetch-pristine.zsh)"
  print
  print -- "- Generated: $(date -u +%Y-%m-%dT%H:%MZ)"
  print -- "- Running kernel: $RUNNING"
  print
  print "## Pinned from: $NIXPKGS"
  print
  print "| Component | Version | URL | Store path | sha256 |"
  print "|---|---|---|---|---|"
  print "| BlueZ | $BLUEZ_VER | $BLUEZ_URL | \`$BLUEZ_TAR\` | $BLUEZ_SHA |"
  print "| Kernel | $KVER | $KURL | \`$KTAR\` | $KSHA |"
  print
  print "## Regenerate / upgrade"
  print
  print "The reviewed artifacts live in \`src/\`: the full patched files"
  print "(\`src/kernel/\`, \`src/bluez/\`) and the generated patches"
  print "(\`src/patches/\`). After a system upgrade, re-run"
  print "\`tools/fetch-pristine.zsh --force\` to refresh \`build/pristine/\`,"
  print "then diff/regenerate with \`tools/make-patches.zsh\` (see README.md)."
  print "Kernel anchor renamed in 6.18: \`joycon_hid_resume\` →"
  print "\`nintendo_hid_resume\`."
} > "$MANIFEST"

print
print "Done:"
print "  $BLUEZ_DIR"
print "  $KERNEL_DIR/drivers/hid/hid-nintendo.c"
print "  $MANIFEST"